spring:
  main:
    allow-circular-references: true
  application:
    name: article-service
  shardingsphere:
    datasource:
      names: m-0, m-1
      m-0:
        type: com.alibaba.druid.pool.DruidDataSource
        url: jdbc:mysql://localhost:3306/springcloud_blog_0?characterEncoding=utf-8&serverTimezone=Asia/Shanghai
        driver-class-name: com.mysql.cj.jdbc.Driver
        username: root
        password:
      m-1:
        type: com.alibaba.druid.pool.DruidDataSource
        url: jdbc:mysql://localhost:3306/springcloud_blog_1?characterEncoding=utf-8&serverTimezone=Asia/Shanghai
        driver-class-name: com.mysql.cj.jdbc.Driver
        username: root
        password:

    sharding:
      tables:
        blog_user:
          actual-data-nodes: m-$->{0..1}.blog_user_$->{0..1}
          keyGenerator:
            column: id
            type: SNOWFLAKE
            props:
              workId: 1
          table-strategy: #分表策略
            inline:
              sharding-column: id
              algorithm-expression: blog_user_$->{id % 2}
        blog_article:
          actual-data-nodes: m-$->{0..1}.blog_article_$->{0..1}
          keyGenerator:
            column: id
            type: SNOWFLAKE
            props:
              workId: 1
          table-strategy: #分表策略
            inline:
              sharding-column: id
              algorithm-expression: blog_article_$->{id % 2}
        blog_article_type:
          actual-data-nodes: m-$->{0..1}.blog_article_type_$->{0..1}
          keyGenerator:
            column: id
            type: SNOWFLAKE
            props:
              workId: 1
          table-strategy: #分表策略
            inline:
              sharding-column: id
              algorithm-expression: blog_article_type_$->{id % 2}
      default-database-strategy: #分库策略
        inline:
          algorithm-expression: m-$->{id % 2}
          sharding-column: id
    props:
      sql:
        show: true
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        username: nacos
        password: nacos
        namespace: cdc60379-e3a5-4bfa-ba8c-658910939f98
      config:
        server-addr: 127.0.0.1:8848
        prefix: ${spring.application.name}
        file-extension: yaml
        namespace: dev
        group: DEFAULT_GROUP
  profiles:
    active: dev

mybatis-plus:
  type-aliases-package: com.wwh.blog.pojo
  mapper-locations: classpath:/mapper/*.xml
  global-config:
    db-config:
      # 驼峰下划线转换
      table-underline: true
      # id生成策略默认采用雪花算法
      id-type: id_worker_str
  configuration:
    # sql打印配置
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
    cache-enabled: false

# 分页配置
pagehelper:
  supportMethodsArguments: true
  reasonable: false
  helperDialect: mysql
  params: count=countSql

dubbo:
  protocol:
    name: dubbo
    port: -1
  cloud:
    subscribed-services: '*'
  scan:
    base-packages: com.wwh.blog



